# Copyright (c) 2016, Thierry Tremblay
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# Reset the lists of suffixes we know how to build
.SUFFIXES:
.SUFFIXES: .c .cpp .h. .hpp .asm .o



# call $(add-rules,SRCDIR,BUILDDIR,EXTRADEPS)
define add-rules
$(info Adding rules: $1 $2 $3)
$(2)/%.asm.o $(2)/%.asm.d: $(1)/%.asm $(3)
	@mkdir -p $$(dir $$@)
	$$(AS) -MD $$(@:%.o=%.d) $$(ASFLAGS) $(local_ASFLAGS) $$(CPPFLAGS:-I%=-I%/) $(local_CPPFLAGS:-I%=-I%/) $$< -o $$($@@:%.d=%.o)

$(2)/%.c.o $(2)/%.c.d: $(1)/%.c $(3)
	@mkdir -p $$(dir $$@)
	$$(CC) -MMD $$(CFLAGS) $(local_CFLAGS) $$(CPPFLAGS) $(local_CPPFLAGS) -c $$< -o $$($@@:%.d=%.o)

$(2)/%.cpp.o $(2)/%.cpp.d: $(1)/%.cpp $(3)
	@mkdir -p $$(dir $$@)
	$$(CXX) -MMD $$(CXXFLAGS) $(local_CXXFLAGS) $$(CPPFLAGS) $(local_CPPFLAGS) -c $$< -o $$($@@:%.d=%.o)

$(2)/%.cc.o $(2)/%.cpp.d: $(1)/%.cc $(3)
	@mkdir -p $$(dir $$@)
	$$(CXX) -MMD $$(CXXFLAGS) $(local_CXXFLAGS) $$(CPPFLAGS) $(local_CPPFLAGS) -c $$< -o $$($@@:%.d=%.o)
endef



# call $(add-module,MODULENAME,MODULEDIR)
define add-module
$(info Adding module $1 at $2)
local_srcdir := $(abspath $2)
local_buildir := $(BUILDDIR)/$1
local_pre_build :=
local_sources :=
local_includes :=
local_DEFINES :=
local_CFLAGS :=
local_CXXFLAGS :=
local_CPPFLAGS :=
local_LDFLAGS :=
local_ASFLAGS :=
include $2/module.mk
local_sources := $$(local_sources:$2/%=%)    # Fix sources to make them relative to MODULEDIR
local_objects := $$(local_sources:%=$(BUILDDIR)/$1/%.o)
OBJECTS := $$(OBJECTS) $$(local_objects)
local_CPPFLAGS += $$(addprefix -D,$$(local_DEFINES)) $$(addprefix -I,$$(local_includes))
$$(eval $$(call add-rules,$$(local_srcdir),$(BUILDDIR)/$1,$$(local_pre_build)))
endef



# call $(find-module,MODULE)
define find-module
match := $$(dir $$(abspath $$(word 1, $$(foreach MODULEPATH, $(MODULEPATHS), $$(wildcard $$(MODULEPATH)/$1/module.mk)))))
ifneq ($$(match),)
    $$(eval $$(call add-module,$$(notdir $$(abspath $$(match))),$$(match)))
else
    $$(error Could not find module $1 in search path)
endif
endef



# call $(load-modules,MODULES)
define load-modules
$(foreach MODULE, $1, $(eval $(call find-module,$(MODULE))))
DEPENDENCIES := $(OBJECTS:%.o=%.d)
endef
